export const practiceQuestionsDS = [
  {
    id: 'array',
    title: 'Array',
    slug: 'array',
    questions: [
      { id: 'array-1', title: 'Find the maximum subarray sum', slug: 'find-maximum-subarray-sum', difficulty: 'easy' },
      { id: 'array-2', title: 'Sort an array of 0s, 1s, and 2s', slug: 'sort-array-0s-1s-2s', difficulty: 'easy' },
      { id: 'array-3', title: 'Rotate an array', slug: 'rotate-array', difficulty: 'easy' },
      { id: 'array-4', title: 'Find the duplicate number', slug: 'find-duplicate-number', difficulty: 'easy' },
      { id: 'array-5', title: 'Merge two sorted arrays', slug: 'merge-two-sorted-arrays', difficulty: 'easy' },
      { id: 'array-6', title: 'Find the missing number', slug: 'find-missing-number', difficulty: 'easy' },
      { id: 'array-7', title: 'Find the intersection of two arrays', slug: 'find-intersection-two-arrays', difficulty: 'medium' },
      { id: 'array-8', title: 'Find the maximum product subarray', slug: 'find-maximum-product-subarray', difficulty: 'medium' },
      { id: 'array-9', title: 'Find the longest consecutive sequence', slug: 'find-longest-consecutive-sequence', difficulty: 'medium' },
      { id: 'array-10', title: 'Find the minimum in a rotated sorted array', slug: 'find-minimum-rotated-sorted-array', difficulty: 'hard' },
      { id: 'array-11', title: 'Find the peak element', slug: 'find-peak-element', difficulty: 'medium' },
      { id: 'array-12', title: 'Find the majority element', slug: 'find-majority-element', difficulty: 'hard' },
      { id: 'array-13', title: 'Trapping rain water', slug: 'trapping-rain-water', difficulty: 'hard' },
      { id: 'array-14', title: 'Find the median of two sorted arrays', slug: 'find-median-two-sorted-arrays', difficulty: 'hard' },
      { id: 'array-15', title: 'Find the kth largest element', slug: 'find-kth-largest-element', difficulty: 'hard' },
    ],
  },
  {
    id: 'matrix',
    title: 'Matrix',
    slug: 'matrix',
    questions: [
      { id: 'matrix-1', title: 'Rotate a matrix', slug: 'rotate-matrix', difficulty: 'easy' },
      { id: 'matrix-2', title: 'Spiral order matrix traversal', slug: 'spiral-order-matrix-traversal', difficulty: 'easy' },
      { id: 'matrix-3', title: 'Search a 2D matrix', slug: 'search-2d-matrix', difficulty: 'easy' },
      { id: 'matrix-4', title: 'Set matrix zeroes', slug: 'set-matrix-zeroes', difficulty: 'easy' },
      { id: 'matrix-5', title: 'Find the number of islands', slug: 'find-number-of-islands', difficulty: 'medium' },
      { id: 'matrix-6', title: 'Matrix multiplication', slug: 'matrix-multiplication', difficulty: 'medium' },
      { id: 'matrix-7', title: 'Transpose of a matrix', slug: 'transpose-matrix', difficulty: 'medium' },
      { id: 'matrix-8', title: 'Word search', slug: 'word-search', difficulty: 'medium' },
      { id: 'matrix-9', title: 'Maximal square', slug: 'maximal-square', difficulty: 'hard' },
      { id: 'matrix-10', title: 'Flood fill algorithm', slug: 'flood-fill-algorithm', difficulty: 'hard' },
      { id: 'matrix-11', title: 'Find the shortest path in a binary matrix', slug: 'find-shortest-path-binary-matrix', difficulty: 'hard' },
      { id: 'matrix-12', title: 'Find the distance of nearest cell having 1', slug: 'find-distance-nearest-cell-having-1', difficulty: 'hard' },
      { id: 'matrix-13', title: 'Count submatrices with all ones', slug: 'count-submatrices-all-ones', difficulty: 'hard' },
      { id: 'matrix-14', title: 'Find the longest increasing path in a matrix', slug: 'find-longest-increasing-path-matrix', difficulty: 'hard' },
      { id: 'matrix-15', title: 'Surrounded regions', slug: 'surrounded-regions', difficulty: 'hard' },
    ],
  },
  {
    id: 'string',
    title: 'String',
    slug: 'string',
    questions: [
      { id: 'string-1', title: 'Reverse a string', slug: 'reverse-string', difficulty: 'easy' },
      { id: 'string-2', title: 'Check if a string is a palindrome', slug: 'check-string-palindrome', difficulty: 'easy' },
      { id: 'string-3', title: 'Find the first non-repeating character', slug: 'find-first-non-repeating-character', difficulty: 'easy' },
      { id: 'string-4', title: 'Check if two strings are anagrams', slug: 'check-strings-anagrams', difficulty: 'easy' },
      { id: 'string-5', title: 'Longest common prefix', slug: 'longest-common-prefix', difficulty: 'medium' },
      { id: 'string-6', title: 'Longest palindromic substring', slug: 'longest-palindromic-substring', difficulty: 'medium' },
      { id: 'string-7', title: 'String to integer (atoi)', slug: 'string-to-integer-atoi', difficulty: 'medium' },
      { id: 'string-8', title: 'Implement strStr()', slug: 'implement-strstr', difficulty: 'easy' },
      { id: 'string-9', title: 'Group anagrams', slug: 'group-anagrams', difficulty: 'medium' },
      { id: 'string-10', title: 'Longest substring without repeating characters', slug: 'longest-substring-without-repeating-characters', difficulty: 'medium' },
      { id: 'string-11', title: 'Count and say', slug: 'count-and-say', difficulty: 'medium' },
      { id: 'string-12', title: 'Valid parentheses', slug: 'valid-parentheses', difficulty: 'easy' },
      { id: 'string-13', title: 'Generate parentheses', slug: 'generate-parentheses', difficulty: 'medium' },
      { id: 'string-14', title: 'Wildcard matching', slug: 'wildcard-matching', difficulty: 'hard' },
      { id: 'string-15', title: 'Find all anagrams in a string', slug: 'find-all-anagrams-in-string', difficulty: 'medium' },
    ],
  },
  {
    id: 'linked-list',
    title: 'Linked List',
    slug: 'linked-list',
    questions: [
      { id: 'linked-list-1', title: 'Reverse a linked list', slug: 'reverse-linked-list', difficulty: 'easy' },
      { id: 'linked-list-2', title: 'Detect a cycle in a linked list', slug: 'detect-cycle-in-linked-list', difficulty: 'medium' },
      { id: 'linked-list-3', title: 'Merge two sorted linked lists', slug: 'merge-two-sorted-linked-lists', difficulty: 'easy' },
      { id: 'linked-list-4', title: 'Remove nth node from end of list', slug: 'remove-nth-node-from-end-of-list', difficulty: 'medium' },
      { id: 'linked-list-5', title: 'Add two numbers represented by linked lists', slug: 'add-two-numbers-represented-by-linked-lists', difficulty: 'medium' },
      { id: 'linked-list-6', title: 'Intersection of two linked lists', slug: 'intersection-of-two-linked-lists', difficulty: 'medium' },
      { id: 'linked-list-7', title: 'Flatten a multilevel doubly linked list', slug: 'flatten-multilevel-doubly-linked-list', difficulty: 'medium' },
      { id: 'linked-list-8', title: 'Palindrome linked list', slug: 'palindrome-linked-list', difficulty: 'easy' },
      { id: 'linked-list-9', title: 'Remove duplicates from sorted list', slug: 'remove-duplicates-from-sorted-list', difficulty: 'easy' },
      { id: 'linked-list-10', title: 'Rotate list', slug: 'rotate-list', difficulty: 'medium' },
      { id: 'linked-list-11', title: 'Split linked list in parts', slug: 'split-linked-list-in-parts', difficulty: 'medium' },
      { id: 'linked-list-12', title: 'Copy list with random pointer', slug: 'copy-list-with-random-pointer', difficulty: 'hard' },
      { id: 'linked-list-13', title: 'Delete node in a linked list', slug: 'delete-node-in-linked-list', difficulty: 'easy' },
      { id: 'linked-list-14', title: 'Swap nodes in pairs', slug: 'swap-nodes-in-pairs', difficulty: 'medium' },
      { id: 'linked-list-15', title: 'Reorder list', slug: 'reorder-list', difficulty: 'medium' },
    ],
  },
  {
    id: 'stack',
    title: 'Stack',
    slug: 'stack',
    questions: [
      { id: 'stack-1', title: 'Implement a stack using arrays', slug: 'implement-stack-using-arrays', difficulty: 'easy' },
      { id: 'stack-2', title: 'Implement a stack using linked list', slug: 'implement-stack-using-linked-list', difficulty: 'easy' },
      { id: 'stack-3', title: 'Check for balanced parentheses', slug: 'check-for-balanced-parentheses', difficulty: 'easy' },
      { id: 'stack-4', title: 'Evaluate reverse polish notation', slug: 'evaluate-reverse-polish-notation', difficulty: 'medium' },
      { id: 'stack-5', title: 'Sort a stack', slug: 'sort-stack', difficulty: 'medium' },
      { id: 'stack-6', title: 'Next greater element', slug: 'next-greater-element', difficulty: 'medium' },
      { id: 'stack-7', title: 'Valid parenthesis string', slug: 'valid-parenthesis-string', difficulty: 'medium' },
      { id: 'stack-8', title: 'Min stack', slug: 'min-stack', difficulty: 'easy' },
      { id: 'stack-9', title: 'Remove k digits', slug: 'remove-k-digits', difficulty: 'medium' },
      { id: 'stack-10', title: 'Basic calculator', slug: 'basic-calculator', difficulty: 'hard' },
      { id: 'stack-11', title: 'Decode string', slug: 'decode-string', difficulty: 'medium' },
      { id: 'stack-12', title: 'Largest rectangle in histogram', slug: 'largest-rectangle-in-histogram', difficulty: 'hard' },
      { id: 'stack-13', title: 'Asteroid collision', slug: 'asteroid-collision', difficulty: 'medium' },
      { id: 'stack-14', title: 'Simplify path', slug: 'simplify-path', difficulty: 'medium' },
      { id: 'stack-15', title: 'Implement a queue using stacks', slug: 'implement-queue-using-stacks', difficulty: 'medium' },
    ],
  },
  {
    id: 'queue',
    title: 'Queue',
    slug: 'queue',
    questions: [
      { id: 'queue-1', title: 'Implement a queue using arrays', slug: 'implement-queue-using-arrays', difficulty: 'easy' },
      { id: 'queue-2', title: 'Implement a queue using linked list', slug: 'implement-queue-using-linked-list', difficulty: 'easy' },
      { id: 'queue-3', title: 'Circular queue implementation', slug: 'circular-queue-implementation', difficulty: 'medium' },
      { id: 'queue-4', title: 'Sliding window maximum', slug: 'sliding-window-maximum', difficulty: 'hard' },
      { id: 'queue-5', title: 'First unique character in a string', slug: 'first-unique-character-in-string', difficulty: 'easy' },
      { id: 'queue-6', title: 'Design hit counter', slug: 'design-hit-counter', difficulty: 'medium' },
      { id: 'queue-7', title: 'Number of recent calls', slug: 'number-of-recent-calls', difficulty: 'easy' },
      { id: 'queue-8', title: 'Implement stack using queues', slug: 'implement-stack-using-queues', difficulty: 'medium' },
      { id: 'queue-9', title: 'The maze', slug: 'the-maze', difficulty: 'medium' },
      { id: 'queue-10', title: 'Shortest path in binary matrix', slug: 'shortest-path-in-binary-matrix', difficulty: 'medium' },
      { id: 'queue-11', title: 'Find the rotten oranges', slug: 'find-rotten-oranges', difficulty: 'medium' },
      { id: 'queue-12', title: 'Open the lock', slug: 'open-the-lock', difficulty: 'medium' },
      { id: 'queue-13', title: 'Course schedule', slug: 'course-schedule', difficulty: 'medium' },
      { id: 'queue-14', title: 'Shortest bridge', slug: 'shortest-bridge', difficulty: 'hard' },
      { id: 'queue-15', title: 'Binary tree level order traversal', slug: 'binary-tree-level-order-traversal', difficulty: 'medium' },
    ],
  },
  {
    id: 'tree',
    title: 'Tree',
    slug: 'tree',
    questions: [
      { id: 'tree-1', title: 'Maximum depth of binary tree', slug: 'maximum-depth-binary-tree', difficulty: 'easy' },
      { id: 'tree-2', title: 'Validate binary search tree', slug: 'validate-binary-search-tree', difficulty: 'medium' },
      { id: 'tree-3', title: 'Invert a binary tree', slug: 'invert-binary-tree', difficulty: 'easy' },
      { id: 'tree-4', title: 'Binary tree level order traversal', slug: 'binary-tree-level-order-traversal', difficulty: 'medium' },
      { id: 'tree-5', title: 'Serialize and deserialize binary tree', slug: 'serialize-deserialize-binary-tree', difficulty: 'hard' },
      { id: 'tree-6', title: 'Subtree of another tree', slug: 'subtree-of-another-tree', difficulty: 'easy' },
      { id: 'tree-7', title: 'Construct binary tree from inorder and preorder traversal', slug: 'construct-binary-tree-inorder-preorder-traversal', difficulty: 'medium' },
      { id: 'tree-8', title: 'Lowest common ancestor of a binary tree', slug: 'lowest-common-ancestor-binary-tree', difficulty: 'medium' },
      { id: 'tree-9', title: 'Binary tree maximum path sum', slug: 'binary-tree-maximum-path-sum', difficulty: 'hard' },
      { id: 'tree-10', title: 'Kth smallest element in a BST', slug: 'kth-smallest-element-bst', difficulty: 'medium' },
      { id: 'tree-11', title: 'Count complete tree nodes', slug: 'count-complete-tree-nodes', difficulty: 'medium' },
      { id: 'tree-12', title: 'Sum of left leaves', slug: 'sum-left-leaves', difficulty: 'easy' },
      { id: 'tree-13', title: 'Diameter of binary tree', slug: 'diameter-binary-tree', difficulty: 'easy' },
      { id: 'tree-14', title: 'Binary tree right side view', slug: 'binary-tree-right-side-view', difficulty: 'medium' },
      { id: 'tree-15', title: 'Find bottom left tree value', slug: 'find-bottom-left-tree-value', difficulty: 'medium' },
    ],
  },
  {
    id: 'heap',
    title: 'Heap',
    slug: 'heap',
    questions: [
      { id: 'heap-1', title: 'Implement a heap', slug: 'implement-heap', difficulty: 'medium' },
      { id: 'heap-2', title: 'Merge k sorted lists', slug: 'merge-k-sorted-lists', difficulty: 'hard' },
      { id: 'heap-3', title: 'Top k frequent elements', slug: 'top-k-frequent-elements', difficulty: 'medium' },
      { id: 'heap-4', title: 'Find the kth largest element in an array', slug: 'find-kth-largest-element-array', difficulty: 'medium' },
      { id: 'heap-5', title: 'Ugly number', slug: 'ugly-number', difficulty: 'medium' },
      { id: 'heap-6', title: 'Super ugly number', slug: 'super-ugly-number', difficulty: 'hard' },
      { id: 'heap-7', title: 'The skyline problem', slug: 'skyline-problem', difficulty: 'hard' },
      { id: 'heap-8', title: 'Kth largest element in a stream', slug: 'kth-largest-element-stream', difficulty: 'medium' },
      { id: 'heap-9', title: 'Find median from data stream', slug: 'find-median-from-data-stream', difficulty: 'hard' },
      { id: 'heap-10', title: 'Sliding window maximum', slug: 'sliding-window-maximum', difficulty: 'hard' },
      { id: 'heap-11', title: 'Find the running median', slug: 'find-running-median', difficulty: 'hard' },
      { id: 'heap-12', title: 'Find the median of a number stream', slug: 'find-median-number-stream', difficulty: 'hard' },
      { id: 'heap-13', title: 'Find the k closest points to the origin', slug: 'find-k-closest-points-origin', difficulty: 'medium' },
      { id: 'heap-14', title: 'Find the kth smallest number in a matrix', slug: 'find-kth-smallest-number-matrix', difficulty: 'hard' },
      { id: 'heap-15', title: 'Find the k closest elements to a given value', slug: 'find-k-closest-elements-to-value', difficulty: 'medium' },
    ],
  },
  {
    id: 'graph',
    title: 'Graph',
    slug: 'graph',
    questions: [
      { id: 'graph-1', title: 'Clone graph', slug: 'clone-graph', difficulty: 'medium' },
      { id: 'graph-2', title: 'Course schedule', slug: 'course-schedule', difficulty: 'medium' },
      { id: 'graph-3', title: 'Number of islands', slug: 'number-of-islands', difficulty: 'medium' },
      { id: 'graph-4', title: 'Pacific Atlantic water flow', slug: 'pacific-atlantic-water-flow', difficulty: 'medium' },
      { id: 'graph-5', title: 'Alien dictionary', slug: 'alien-dictionary', difficulty: 'hard' },
      { id: 'graph-6', title: 'Network delay time', slug: 'network-delay-time', difficulty: 'medium' },
      { id: 'graph-7', title: 'Cheapest flights within k stops', slug: 'cheapest-flights-within-k-stops', difficulty: 'medium' },
      { id: 'graph-8', title: 'Find the city with the smallest number of neighbors at a threshold distance', slug: 'find-city-smallest-neighbors-threshold-distance', difficulty: 'medium' },
      { id: 'graph-9', title: 'All paths from source to target', slug: 'all-paths-from-source-to-target', difficulty: 'medium' },
      { id: 'graph-10', title: 'Redundant connection', slug: 'redundant-connection', difficulty: 'medium' },
      { id: 'graph-11', title: 'Minimum height trees', slug: 'minimum-height-trees', difficulty: 'medium' },
      { id: 'graph-12', title: 'Word ladder', slug: 'word-ladder', difficulty: 'medium' },
      { id: 'graph-13', title: 'Word ladder II', slug: 'word-ladder-ii', difficulty: 'hard' },
      { id: 'graph-14', title: 'Word search', slug: 'word-search', difficulty: 'medium' },
      { id: 'graph-15', title: 'Word search II', slug: 'word-search-ii', difficulty: 'hard' },
    ],
  },
  {
    id: 'trie',
    title: 'Trie',
    slug: 'trie',
    questions: [
      { id: 'trie-1', title: 'Implement a trie', slug: 'implement-trie', difficulty: 'medium' },
      { id: 'trie-2', title: 'Add and search word', slug: 'add-and-search-word', difficulty: 'medium' },
      { id: 'trie-3', title: 'Word search II', slug: 'word-search-ii', difficulty: 'hard' },
      { id: 'trie-4', title: 'Implement magic dictionary', slug: 'implement-magic-dictionary', difficulty: 'medium' },
      { id: 'trie-5', title: 'Longest word in dictionary', slug: 'longest-word-in-dictionary', difficulty: 'medium' },
      { id: 'trie-6', title: 'Replace words', slug: 'replace-words', difficulty: 'medium' },
      { id: 'trie-7', title: 'Implement autocomplete system', slug: 'implement-autocomplete-system', difficulty: 'hard' },
      { id: 'trie-8', title: 'Stream of characters', slug: 'stream-of-characters', difficulty: 'hard' },
      { id: 'trie-9', title: 'Implement a prefix tree', slug: 'implement-prefix-tree', difficulty: 'medium' },
      { id: 'trie-10', title: 'Short encoding of words', slug: 'short-encoding-words', difficulty: 'medium' },
      { id: 'trie-11', title: 'Implement a trie II', slug: 'implement-trie-ii', difficulty: 'medium' },
      { id: 'trie-12', title: 'Design search auto-complete system', slug: 'design-search-auto-complete-system', difficulty: 'hard' },
      { id: 'trie-13', title: 'Longest common prefix', slug: 'longest-common-prefix', difficulty: 'medium' },
      { id: 'trie-14', title: 'Word squares', slug: 'word-squares', difficulty: 'hard' },
      { id: 'trie-15', title: 'Implement magic dictionary II', slug: 'implement-magic-dictionary-ii', difficulty: 'medium' },
    ],
  },
  {
    id: 'hash-table',
    title: 'Hash Table',
    slug: 'hash-table',
    questions: [
      { id: 'hash-table-1', title: 'Two sum', slug: 'two-sum', difficulty: 'easy' },
      { id: 'hash-table-2', title: 'Group anagrams', slug: 'group-anagrams', difficulty: 'medium' },
      { id: 'hash-table-3', title: 'Longest substring without repeating characters', slug: 'longest-substring-without-repeating-characters', difficulty: 'medium' },
      { id: 'hash-table-4', title: 'Valid sudoku', slug: 'valid-sudoku', difficulty: 'medium' },
      { id: 'hash-table-5', title: 'Isomorphic strings', slug: 'isomorphic-strings', difficulty: 'easy' },
      { id: 'hash-table-6', title: 'Word pattern', slug: 'word-pattern', difficulty: 'easy' },
      { id: 'hash-table-7', title: 'Minimum index sum of two lists', slug: 'minimum-index-sum-two-lists', difficulty: 'easy' },
      { id: 'hash-table-8', title: 'Find all anagrams in a string', slug: 'find-all-anagrams-in-string', difficulty: 'medium' },
      { id: 'hash-table-9', title: 'Four sum II', slug: 'four-sum-ii', difficulty: 'medium' },
      { id: 'hash-table-10', title: 'Longest palindrome', slug: 'longest-palindrome', difficulty: 'easy' },
      { id: 'hash-table-11', title: 'Intersection of two arrays', slug: 'intersection-of-two-arrays', difficulty: 'easy' },
      { id: 'hash-table-12', title: 'Happy number', slug: 'happy-number', difficulty: 'easy' },
      { id: 'hash-table-13', title: 'Repeated DNA sequences', slug: 'repeated-dna-sequences', difficulty: 'medium' },
      { id: 'hash-table-14', title: 'Find the difference', slug: 'find-the-difference', difficulty: 'easy' },
      { id: 'hash-table-15', title: 'Contains duplicate', slug: 'contains-duplicate', difficulty: 'easy' },
    ],
  },
] as const;

export const practiceQuestionsA = [
  {
    id: 'sorting',
    title: 'Sorting Algorithms',
    slug: 'sorting-algorithms',
    questions: [
      { id: 'sorting-1', title: 'Bubble Sort', slug: 'bubble-sort', difficulty: 'Easy' },
      { id: 'sorting-2', title: 'Selection Sort', slug: 'selection-sort', difficulty: 'Easy' },
      { id: 'sorting-3', title: 'Insertion Sort', slug: 'insertion-sort', difficulty: 'Easy' },
      { id: 'sorting-4', title: 'Merge Sort', slug: 'merge-sort', difficulty: 'Medium' },
      { id: 'sorting-5', title: 'Quick Sort', slug: 'quick-sort', difficulty: 'Medium' },
      { id: 'sorting-6', title: 'Heap Sort', slug: 'heap-sort', difficulty: 'Medium' },
      { id: 'sorting-7', title: 'Counting Sort', slug: 'counting-sort', difficulty: 'Medium' },
      { id: 'sorting-8', title: 'Radix Sort', slug: 'radix-sort', difficulty: 'Medium' },
      { id: 'sorting-9', title: 'Bucket Sort', slug: 'bucket-sort', difficulty: 'Medium' },
      { id: 'sorting-10', title: 'Cocktail Shaker Sort', slug: 'cocktail-shaker-sort', difficulty: 'Medium' },
      { id: 'sorting-11', title: 'Shell Sort', slug: 'shell-sort', difficulty: 'Hard' },
      { id: 'sorting-12', title: 'Gnome Sort', slug: 'gnome-sort', difficulty: 'Easy' },
      { id: 'sorting-13', title: 'Pigeonhole Sort', slug: 'pigeonhole-sort', difficulty: 'Medium' },
      { id: 'sorting-14', title: 'Tree Sort', slug: 'tree-sort', difficulty: 'Medium' },
      { id: 'sorting-15', title: 'Tim Sort', slug: 'tim-sort', difficulty: 'Hard' },
      { id: 'sorting-16', title: 'Comb Sort', slug: 'comb-sort', difficulty: 'Medium' },
      { id: 'sorting-17', title: 'Odd-Even Sort', slug: 'odd-even-sort', difficulty: 'Easy' },
      { id: 'sorting-18', title: 'Bitonic Sort', slug: 'bitonic-sort', difficulty: 'Hard' },
      { id: 'sorting-19', title: 'Stooge Sort', slug: 'stooge-sort', difficulty: 'Medium' },
      { id: 'sorting-20', title: 'Pancake Sort', slug: 'pancake-sort', difficulty: 'Medium' },
    ],
  },
  {
    id: 'searching',
    title: 'Searching Algorithms',
    slug: 'searching-algorithms',
    questions: [
      { id: 'searching-1', title: 'Linear Search', slug: 'linear-search', difficulty: 'Easy' },
      { id: 'searching-2', title: 'Binary Search', slug: 'binary-search', difficulty: 'Easy' },
      { id: 'searching-3', title: 'Jump Search', slug: 'jump-search', difficulty: 'Medium' },
      { id: 'searching-4', title: 'Exponential Search', slug: 'exponential-search', difficulty: 'Medium' },
      { id: 'searching-5', title: 'Interpolation Search', slug: 'interpolation-search', difficulty: 'Medium' },
      { id: 'searching-6', title: 'Fibonacci Search', slug: 'fibonacci-search', difficulty: 'Medium' },
      { id: 'searching-7', title: 'Ternary Search', slug: 'ternary-search', difficulty: 'Medium' },
      { id: 'searching-8', title: 'Sublist Search', slug: 'sublist-search', difficulty: 'Medium' },
      { id: 'searching-9', title: 'Matrix Search', slug: 'matrix-search', difficulty: 'Medium' },
      { id: 'searching-10', title: 'Peak Element', slug: 'peak-element', difficulty: 'Medium' },
      { id: 'searching-11', title: 'Find the smallest missing number', slug: 'find-smallest-missing-number', difficulty: 'Easy' },
      { id: 'searching-12', title: 'Find first and last position of an element', slug: 'find-first-last-position', difficulty: 'Medium' },
      { id: 'searching-13', title: 'Find the majority element', slug: 'find-majority-element', difficulty: 'Easy' },
      { id: 'searching-14', title: 'Find the kth largest element', slug: 'find-kth-largest-element', difficulty: 'Medium' },
      { id: 'searching-15', title: 'Find a pair with a given sum', slug: 'find-pair-with-sum', difficulty: 'Easy' },
      { id: 'searching-16', title: 'Find an element in a rotated sorted array', slug: 'find-in-rotated-array', difficulty: 'Medium' },
      { id: 'searching-17', title: 'Find an element in a 2D matrix', slug: 'find-element-in-2d-matrix', difficulty: 'Medium' },
      { id: 'searching-18', title: 'Find the intersection of two sorted arrays', slug: 'intersection-of-sorted-arrays', difficulty: 'Easy' },
      { id: 'searching-19', title: 'Find the missing number in an array', slug: 'missing-number-in-array', difficulty: 'Easy' },
      { id: 'searching-20', title: 'Find the duplicate number in an array', slug: 'duplicate-number-in-array', difficulty: 'Medium' },
    ],
  },
  {
    id: 'dynamic-programming',
    title: 'Dynamic Programming Algorithms',
    slug: 'dynamic-programming',
    questions: [
      { id: 'dp-1', title: 'Fibonacci Sequence', slug: 'fibonacci-sequence', difficulty: 'Easy' },
      { id: 'dp-2', title: 'Knapsack Problem', slug: 'knapsack-problem', difficulty: 'Medium' },
      { id: 'dp-3', title: 'Longest Common Subsequence', slug: 'longest-common-subsequence', difficulty: 'Medium' },
      { id: 'dp-4', title: 'Longest Increasing Subsequence', slug: 'longest-increasing-subsequence', difficulty: 'Medium' },
      { id: 'dp-5', title: 'Coin Change Problem', slug: 'coin-change-problem', difficulty: 'Medium' },
      { id: 'dp-6', title: 'Matrix Chain Multiplication', slug: 'matrix-chain-multiplication', difficulty: 'Hard' },
      { id: 'dp-7', title: 'Edit Distance', slug: 'edit-distance', difficulty: 'Medium' },
      { id: 'dp-8', title: 'Subset Sum Problem', slug: 'subset-sum-problem', difficulty: 'Medium' },
      { id: 'dp-9', title: 'Rod Cutting Problem', slug: 'rod-cutting-problem', difficulty: 'Medium' },
      { id: 'dp-10', title: 'Word Break Problem', slug: 'word-break-problem', difficulty: 'Hard' },
      { id: 'dp-11', title: 'Palindrome Partitioning', slug: 'palindrome-partitioning', difficulty: 'Hard' },
      { id: 'dp-12', title: 'Unique Paths', slug: 'unique-paths', difficulty: 'Medium' },
      { id: 'dp-13', title: 'Number of Longest Increasing Subsequence', slug: 'number-of-longest-increasing-subsequence', difficulty: 'Hard' },
      { id: 'dp-14', title: 'Count of Subset Sum', slug: 'count-of-subset-sum', difficulty: 'Medium' },
      { id: 'dp-15', title: 'Equal Sum Partition', slug: 'equal-sum-partition', difficulty: 'Medium' },
      { id: 'dp-16', title: 'Maximum Subarray Sum', slug: 'maximum-subarray-sum', difficulty: 'Easy' },
      { id: 'dp-17', title: 'Partition Equal Subset Sum', slug: 'partition-equal-subset-sum', difficulty: 'Medium' },
      { id: 'dp-18', title: 'Best Time to Buy and Sell Stock', slug: 'best-time-to-buy-sell-stock', difficulty: 'Easy' },
      { id: 'dp-19', title: 'House Robber Problem', slug: 'house-robber-problem', difficulty: 'Medium' },
      { id: 'dp-20', title: 'Minimum Path Sum', slug: 'minimum-path-sum', difficulty: 'Medium' },
    ],
  },
  {
    id: 'greedy',
    title: 'Greedy Algorithms',
    slug: 'greedy-algorithms',
    questions: [
      { id: 'greedy-1', title: 'Activity Selection Problem', slug: 'activity-selection-problem', difficulty: 'Easy' },
      { id: 'greedy-2', title: 'Huffman Coding', slug: 'huffman-coding', difficulty: 'Hard' },
      { id: 'greedy-3', title: 'Fractional Knapsack Problem', slug: 'fractional-knapsack-problem', difficulty: 'Easy' },
      { id: 'greedy-4', title: 'Job Sequencing Problem', slug: 'job-sequencing-problem', difficulty: 'Medium' },
      { id: 'greedy-5', title: 'Prim\'s Algorithm', slug: 'prims-algorithm', difficulty: 'Medium' },
      { id: 'greedy-6', title: 'Kruskal\'s Algorithm', slug: 'kruskals-algorithm', difficulty: 'Medium' },
      { id: 'greedy-7', title: 'Dijkstra\'s Algorithm', slug: 'dijkstras-algorithm', difficulty: 'Medium' },
      { id: 'greedy-8', title: 'Minimum Spanning Tree', slug: 'minimum-spanning-tree', difficulty: 'Medium' },
      { id: 'greedy-9', title: 'Optimal Merge Pattern', slug: 'optimal-merge-pattern', difficulty: 'Medium' },
      { id: 'greedy-10', title: 'Greedy Coloring of Graph', slug: 'greedy-coloring-of-graph', difficulty: 'Medium' },
      { id: 'greedy-11', title: 'Greedy Approach for Job Scheduling', slug: 'greedy-job-scheduling', difficulty: 'Medium' },
      { id: 'greedy-12', title: 'Coin Change Problem', slug: 'coin-change-problem', difficulty: 'Easy' },
      { id: 'greedy-13', title: 'Minimum Number of Platforms Required', slug: 'minimum-platforms', difficulty: 'Medium' },
      { id: 'greedy-14', title: 'Maximum Product of Two Numbers', slug: 'maximum-product-two-numbers', difficulty: 'Easy' },
      { id: 'greedy-15', title: 'Greedy Algorithm for Fractional Knapsack', slug: 'fractional-knapsack', difficulty: 'Easy' },
      { id: 'greedy-16', title: 'Choosing the best route', slug: 'best-route-selection', difficulty: 'Medium' },
      { id: 'greedy-17', title: 'Greedy approach for maximum sum', slug: 'greedy-maximum-sum', difficulty: 'Medium' },
      { id: 'greedy-18', title: 'Efficient event scheduling', slug: 'efficient-event-scheduling', difficulty: 'Medium' },
      { id: 'greedy-19', title: 'Minimum cost for ropes', slug: 'minimum-cost-for-ropes', difficulty: 'Easy' },
      { id: 'greedy-20', title: 'Find the maximum number of activities', slug: 'maximum-number-of-activities', difficulty: 'Easy' },
    ],
  },
  {
    id: 'backtracking',
    title: 'Backtracking Algorithms',
    slug: 'backtracking-algorithms',
    questions: [
      { id: 'backtracking-1', title: 'N-Queens Problem', slug: 'n-queens-problem', difficulty: 'Hard' },
      { id: 'backtracking-2', title: 'Sudoku Solver', slug: 'sudoku-solver', difficulty: 'Hard' },
      { id: 'backtracking-3', title: 'Generate Parentheses', slug: 'generate-parentheses', difficulty: 'Medium' },
      { id: 'backtracking-4', title: 'Combination Sum', slug: 'combination-sum', difficulty: 'Medium' },
      { id: 'backtracking-5', title: 'Permutations', slug: 'permutations', difficulty: 'Medium' },
      { id: 'backtracking-6', title: 'Subsets', slug: 'subsets', difficulty: 'Medium' },
      { id: 'backtracking-7', title: 'Letter Combinations of a Phone Number', slug: 'letter-combinations', difficulty: 'Medium' },
      { id: 'backtracking-8', title: 'Word Search', slug: 'word-search', difficulty: 'Medium' },
      { id: 'backtracking-9', title: 'Graph Coloring', slug: 'graph-coloring', difficulty: 'Hard' },
      { id: 'backtracking-10', title: 'Word Break', slug: 'word-break', difficulty: 'Hard' },
      { id: 'backtracking-11', title: 'Combination Sum II', slug: 'combination-sum-ii', difficulty: 'Medium' },
      { id: 'backtracking-12', title: 'Solve the 8-Puzzle Problem', slug: '8-puzzle', difficulty: 'Hard' },
      { id: 'backtracking-13', title: 'Find Hamiltonian Path', slug: 'hamiltonian-path', difficulty: 'Hard' },
      { id: 'backtracking-14', title: 'Knights Tour', slug: 'knights-tour', difficulty: 'Hard' },
      { id: 'backtracking-15', title: 'Solving Rat in a Maze Problem', slug: 'rat-in-maze', difficulty: 'Medium' },
      { id: 'backtracking-16', title: 'Generate All Subsets of a Set', slug: 'generate-subsets', difficulty: 'Medium' },
      { id: 'backtracking-17', title: 'Partition Equal Subset Sum', slug: 'partition-equal-subset', difficulty: 'Hard' },
      { id: 'backtracking-18', title: 'Palindromic Substrings', slug: 'palindromic-substrings', difficulty: 'Medium' },
      { id: 'backtracking-19', title: 'All Possible Combinations of Numbers', slug: 'all-possible-combinations', difficulty: 'Medium' },
      { id: 'backtracking-20', title: 'All Paths From Source to Target', slug: 'paths-source-target', difficulty: 'Medium' },
    ],
  },
  {
    id: 'divide-and-conquer',
    title: 'Divide and Conquer Algorithms',
    slug: 'divide-and-conquer-algorithms',
    questions: [
      { id: 'divide-and-conquer-1', title: 'Binary Search', slug: 'binary-search', difficulty: 'Easy' },
      { id: 'divide-and-conquer-2', title: 'Merge Sort', slug: 'merge-sort', difficulty: 'Medium' },
      { id: 'divide-and-conquer-3', title: 'Quick Sort', slug: 'quick-sort', difficulty: 'Medium' },
      { id: 'divide-and-conquer-4', title: 'Strassen\'s Matrix Multiplication', slug: 'strassens-matrix-multiplication', difficulty: 'Hard' },
      { id: 'divide-and-conquer-5', title: 'Closest Pair of Points', slug: 'closest-pair-of-points', difficulty: 'Hard' },
      { id: 'divide-and-conquer-6', title: 'Karatsuba Algorithm', slug: 'karatsuba-algorithm', difficulty: 'Hard' },
      { id: 'divide-and-conquer-7', title: 'Maximum Subarray Sum', slug: 'maximum-subarray-sum', difficulty: 'Medium' },
      { id: 'divide-and-conquer-8', title: 'Count Inversions in an Array', slug: 'count-inversions', difficulty: 'Medium' },
      { id: 'divide-and-conquer-9', title: 'Matrix Exponentiation', slug: 'matrix-exponentiation', difficulty: 'Hard' },
      { id: 'divide-and-conquer-10', title: 'Tiling Problem', slug: 'tiling-problem', difficulty: 'Medium' },
      { id: 'divide-and-conquer-11', title: 'Find the majority element', slug: 'majority-element', difficulty: 'Easy' },
      { id: 'divide-and-conquer-12', title: 'Maximum Product Subarray', slug: 'maximum-product-subarray', difficulty: 'Medium' },
      { id: 'divide-and-conquer-13', title: 'Maximum Sum Subarray using Divide and Conquer', slug: 'maximum-sum-subarray', difficulty: 'Medium' },
      { id: 'divide-and-conquer-14', title: 'Maximum Sum Rectangle in a 2D Matrix', slug: 'maximum-sum-rectangle', difficulty: 'Hard' },
      { id: 'divide-and-conquer-15', title: 'Maximum Sum Subsequence Non-Adjacent Elements', slug: 'maximum-sum-subsequence', difficulty: 'Medium' },
      { id: 'divide-and-conquer-16', title: 'Count of Inversions in a given array', slug: 'count-inversions', difficulty: 'Medium' },
      { id: 'divide-and-conquer-17', title: 'Maximum Sum Increasing Subsequence', slug: 'maximum-sum-increasing-subsequence', difficulty: 'Hard' },
      { id: 'divide-and-conquer-18', title: 'Maximum Sum Bitonic Subsequence', slug: 'maximum-sum-bitonic-subsequence', difficulty: 'Hard' },
      { id: 'divide-and-conquer-19', title: 'Longest Bitonic Subsequence', slug: 'longest-bitonic-subsequence', difficulty: 'Hard' },
      { id: 'divide-and-conquer-20', title: 'Maximum Length Chain of Pairs', slug: 'maximum-length-chain-pairs', difficulty: 'Medium' },
    ],
  },
  {
    id: 'graph',
    title: 'Graph Algorithms',
    slug: 'graph-algorithms',
    questions: [
      { id: 'graph-1', title: 'Breadth First Search', slug: 'breadth-first-search', difficulty: 'Easy' },
      { id: 'graph-2', title: 'Depth First Search', slug: 'depth-first-search', difficulty: 'Easy' },
      { id: 'graph-3', title: 'Topological Sort', slug: 'topological-sort', difficulty: 'Medium' },
      { id: 'graph-4', title: 'Dijkstra\'s Algorithm', slug: 'dijkstras-algorithm', difficulty: 'Medium' },
      { id: 'graph-5', title: 'Bellman Ford Algorithm', slug: 'bellman-ford-algorithm', difficulty: 'Hard' },
      { id: 'graph-6', title: 'Floyd Warshall Algorithm', slug: 'floyd-warshall-algorithm', difficulty: 'Hard' },
      { id: 'graph-7', title: 'Prim\'s Algorithm', slug: 'prims-algorithm', difficulty: 'Medium' },
      { id: 'graph-8', title: 'Kruskal\'s Algorithm', slug: 'kruskals-algorithm', difficulty: 'Medium' },
      { id: 'graph-9', title: 'Articulation Points (Cut Vertices)', slug: 'articulation-points', difficulty: 'Hard' },
      { id: 'graph-10', title: 'Bridges in a Graph', slug: 'bridges-in-graph', difficulty: 'Hard' },
      { id: 'graph-11', title: 'Strongly Connected Components', slug: 'strongly-connected-components', difficulty: 'Hard' },
      { id: 'graph-12', title: 'Eulerian Path and Circuit', slug: 'eulerian-path-circuit', difficulty: 'Medium' },
      { id: 'graph-13', title: 'Hamiltonian Cycle', slug: 'hamiltonian-cycle', difficulty: 'Hard' },
      { id: 'graph-14', title: 'Detect Cycle in a Directed Graph', slug: 'detect-cycle-directed-graph', difficulty: 'Medium' },
      { id: 'graph-15', title: 'Detect Cycle in an Undirected Graph', slug: 'detect-cycle-undirected-graph', difficulty: 'Medium' },
      { id: 'graph-16', title: 'Minimum Spanning Tree', slug: 'minimum-spanning-tree', difficulty: 'Medium' },
      { id: 'graph-17', title: 'Shortest Path in a Directed Acyclic Graph', slug: 'shortest-path-dag', difficulty: 'Medium' },
      { id: 'graph-18', title: 'Travelling Salesman Problem', slug: 'travelling-salesman-problem', difficulty: 'Hard' },
      { id: 'graph-19', title: 'Minimum Cost Path', slug: 'minimum-cost-path', difficulty: 'Medium' },
      { id: 'graph-20', title: 'Minimum Cost to Connect All Cities', slug: 'minimum-cost-connect-cities', difficulty: 'Hard' },
    ],
  },
  {
    id: 'tree',
    title: 'Tree Algorithms',
    slug: 'tree-algorithms',
    questions: [
      { id: 'tree-1', title: 'Binary Tree Traversal', slug: 'binary-tree-traversal', difficulty: 'Easy' },
      { id: 'tree-2', title: 'Binary Search Tree', slug: 'binary-search-tree', difficulty: 'Easy' },
      { id: 'tree-3', title: 'Lowest Common Ancestor', slug: 'lowest-common-ancestor', difficulty: 'Medium' },
      { id: 'tree-4', title: 'Check for Balanced Tree', slug: 'check-balanced-tree', difficulty: 'Easy' },
      { id: 'tree-5', title: 'Check for Symmetric Tree', slug: 'check-symmetric-tree', difficulty: 'Easy' },
      { id: 'tree-6', title: 'Maximum Depth of Binary Tree', slug: 'maximum-depth-binary-tree', difficulty: 'Easy' },
      { id: 'tree-7', title: 'Construct Binary Tree from Inorder and Postorder Traversal', slug: 'construct-binary-tree-inorder-postorder', difficulty: 'Medium' },
      { id: 'tree-8', title: 'Construct Binary Tree from Preorder and Inorder Traversal', slug: 'construct-binary-tree-preorder-inorder', difficulty: 'Medium' },
      { id: 'tree-9', title: 'Construct Binary Search Tree from Preorder Traversal', slug: 'construct-bst-preorder', difficulty: 'Medium' },
      { id: 'tree-10', title: 'Inorder Successor in Binary Search Tree', slug: 'inorder-successor-bst', difficulty: 'Medium' },
      { id: 'tree-11', title: 'Populating Next Right Pointers in Each Node', slug: 'populating-next-right-pointers', difficulty: 'Medium' },
      { id: 'tree-12', title: 'Serialize and Deserialize Binary Tree', slug: 'serialize-deserialize-binary-tree', difficulty: 'Hard' },
      { id: 'tree-13', title: 'Maximum Path Sum in Binary Tree', slug: 'maximum-path-sum-binary-tree', difficulty: 'Hard' },
      { id: 'tree-14', title: 'Count Univalue Subtrees', slug: 'count-univalue-subtrees', difficulty: 'Medium' },
    ],
  },
] as const;
